// study-update-vue/study-update-vue/08 vue3+ts/004 vue3_ts_antd_demo/src/pages/login/index.vue
<template>
  <div>
    <a-form
      :label-col="labelCol"
      :wrapper-col="wrapperCol"
      :rules="rules"
      :model="admin"
      ref="formRef"
    >
      <a-form-item label="用户名" name="name">
        <a-input v-model:value="admin.name"></a-input>
      </a-form-item>
      <a-form-item label="密码" name="password">
        <a-input type="password" v-model:value="admin.password"></a-input>
      </a-form-item>
      <a-button type="primary" @click="onSubmit">登录</a-button>
    </a-form>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, toRaw } from "vue";
import { login } from "../../api/login";
import { add } from "../../utils/storage";
import { message } from "ant-design-vue";
import { useRouter } from "vue-router";
interface IAdmin {
  name: string;
  password: string;
}

export default defineComponent({
  name: "login",
  setup() {
    // message.info("寒云老师我爱你");
    const formRef = ref();
    const router = useRouter();
    const admin = reactive<IAdmin>({
      name: "",
      password: ""
    });

    const rules = {
      name: [{ required: true, message: "请输入账号", trigger: "blur" }],
      password: [{ required: true, message: "请输入密码", trigger: "blur" }]
    };

    const onSubmit = () => {
      // console.log(admin.name, admin.password);
      // console.log(formRef._value);
      // const a = formRef.value.validate();
      // console.log(a);
      formRef.value
        .validate()
        .then(() => {
          /* 需要将被proxy修饰的对象转换为原始的对象 */
          login(toRaw(admin))
            .then(response => {
              if (response.data.msg === "success") {
                const { token } = response.data.data || "";
                // console.log(token);
                add("token", token);
                message.info(response.data.msg);
                console.log(router);
                router.push("/user");
              } else {
                message.info(response.data.msg);
              }
            })
            .catch(error => {
              console.log("error", error);
            });
        })
        .catch(() => {});
    };
    return {
      formRef,
      admin,
      onSubmit,
      labelCol: { span: 6 },
      wrapperCol: { span: 12 },
      rules,
      router
    };
  }
});
</script>

<style scoped>
</style>

// study-update-react/study-update-react/12react+ts/react-ts-hzeroui/src/pages/login/Index.tsx
import { Button, Form, Input, message } from "antd";
import React, { Component } from "react";
import { RouteComponentProps, withRouter } from "react-router-dom";
import { IAdmin, login } from "../../api/login";
import { set } from "../../utils/storage";

/* react-ts使用编程式导航时，先记住这么做，目前知识量不足以理解
    1.声明IProps接口继承 RouteComponentProps接口
    2.导出组件时，使用withRouter高级组件
*/

interface IProps extends RouteComponentProps {}
class Index extends Component<IProps> {
  handleSubmit = (values: IAdmin) => {
    login(values)
      .then((response) => {
        const { code, msg } = response.data;
        if (code === 0) {
          const { token } = response.data.data;
          set("token", token);
          message.success(msg);
          this.props.history.push("/home")
        }else {
            message.error(msg)
        }
      })
  };
  render() {
    return (
      <>
        <Form
          labelCol={{ span: 9 }}
          wrapperCol={{ span: 6 }}
          onFinish={this.handleSubmit}
        >
          <Form.Item
            label="用户名"
            name="name"
            rules={[
              {
                type: "string",
                required: true,
                message: "用户名不可以为空",
              },
            ]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="密码"
            name="password"
            rules={[
              {
                type: "string",
                required: true,
                message: "密码不可以为空",
              },
            ]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item wrapperCol={{ offset: 13, span: 6 }}>
            {/* 表单中的button具有原生事件，submit和reset */}
            <Button type="primary" htmlType="submit">
              登录
            </Button>
            <Button type="primary" htmlType="reset">
              清空
            </Button>
          </Form.Item>
        </Form>
      </>
    );
  }
}

export default withRouter(Index)
